name = "cf-shortlinks"
main = "src/index.js"
compatibility_date = "2022-07-20"

minify = true

workers_dev = true

[[kv_namespaces]]
binding = "SHORTLINKS"
id = "33c693b6e1eb4be9bf7bccaa21da5a33"
preview_id = "013d0cafd19d4bc19209d45b891f4d30"

[[kv_namespaces]]
binding = "SHORTDOMAINS"
id = "4573460fa4c64f2596ed0c0527ce3b6d"
preview_id = "8b8875e4a9b14757935c7a835d54c72e"

[vars]
BASE_HOSTNAME = "tarper24.workers.dev"
REDIRECT_CODE = 301

[env.dev]
workers_dev = false

[env.dev.vars]
BASE_HOSTNAME = "dev.tarper24.net"
REDIRECT_CODE = 301

[[env.dev.kv_namespaces]]
binding = "SHORTLINKS"
id = "78add87baf0f45ccb1d0cdb0160faf4c"

[[env.dev.kv_namespaces]]
binding = "SHORTDOMAINS"
id = "8d9b27f97aaf4187beb51b7674c94a6a"

[[env.dev.routes]]
pattern = "go.dev.tarper24.net"
custom_domain = true

[[env.dev.routes]]
pattern = "tv.dev.tarper24.net"
custom_domain = true

[[env.dev.routes]]
pattern = "twitch.dev.tarper24.net"
custom_domain = true

[[env.dev.routes]]
pattern = "twitter.dev.tarper24.net"
custom_domain = true

[env.prod]
workers_dev = false

[env.prod.vars]
BASE_HOSTNAME = "t24.co"
REDIRECT_CODE = 301

[[env.prod.kv_namespaces]]
binding = "SHORTLINKS"
id = "ef8d1995d4a14d079e5a4a600db6b5d4"

[[env.prod.kv_namespaces]]
binding = "SHORTDOMAINS"
id = "bc747d494d6f4b3780655dd14dff3e15"

[[env.prod.routes]]
pattern = "go.t24.co"
custom_domain = true

[[env.prod.routes]]
pattern = "tv.t24.co"
custom_domain = true

[[env.prod.routes]]
pattern = "twitch.t24.co"
custom_domain = true

[[env.prod.routes]]
pattern = "twitter.t24.co"
custom_domain = true

[[env.prod.routes]]
pattern = "gg.t24.co"
custom_domain = true

[[env.prod.routes]]
pattern = "guilded.t24.co"
custom_domain = true

[[env.prod.routes]]
pattern = "gh.t24.co"
custom_domain = true

[[env.prod.routes]]
pattern = "github.t24.co"
custom_domain = true

[[env.prod.routes]]
pattern = "yt.t24.co"
custom_domain = true

[[env.prod.routes]]
pattern = "youtube.t24.co"
custom_domain = true

[[env.prod.routes]]
pattern = "steam.t24.co"
custom_domain = true

[[env.prod.routes]]
pattern = "games.t24.co"
custom_domain = true
